### ISSUE TITLE
Midi schematic

### ISSUE THREAD

**Issue by drummerclint** [vanvught/rpidmx512#100]
Happy new year Arjan!

DS3231 RTC clock appears to be working nicely!  Thank you!

Was wondering if you can share the schematic for your MIDI / balanced audio board yet.  At the moment I just need the midi part as I wouldn't mind building it into this particular version.

re: interfacing with Jame's BLT, it works quite nicely, I'm going to film a quick video demonstrating it, controlling Resolume via a LTC, via a CDJ.

Thanks in advance,
Clint

**Comment by vanvught** [comment]
Hi Clint, happy new year!

As I was working on finishing the WS28xx display support and implementing TCNet specification V3.3.3, I did not have the time working on the hardware. 

The prebuild LTC SMPTE V2.4 is here -> [https://drive.google.com/open?id=169nmTLxNIRca2DcmwZ_8m6YfLBVkxkkM](https://drive.google.com/open?id=169nmTLxNIRca2DcmwZ_8m6YfLBVkxkkM)

I have created a single issue #102 for all the website updates. Therefore closing this one.

Groet, Arjan

**Comment by drummerclint** [comment]
That's great! Thanks Arjan!

**Comment by hippyau** [comment]
Hey Arjan,
   Is there a board that has both MIDI and LTC connections so that one can take advantage of LTC>MIDI or MIDI>LTC or ARTNET>MIDI&LTC etc :)

**Comment by vanvught** [comment]
Hi Hippy, yes there is. See also the item "Add schematic, PCB and BOM for the next LTC SMPTE"  in #102 :)
![Schermafbeelding 2020-06-05 om 15 23 36](https://user-images.githubusercontent.com/4319913/83881186-8fc4b400-a740-11ea-8e40-81803d6b1b57.png)

![Schermafbeelding 2020-06-05 om 15 25 07](https://user-images.githubusercontent.com/4319913/83881343-c4d10680-a740-11ea-93e2-b0e4234ed07e.png)

![IMG_3469](https://user-images.githubusercontent.com/4319913/83881071-6a37aa80-a740-11ea-847b-2499cd2b795e.png)

**Comment by hippyau** [comment]
Arjan... This is epic!!

Thanks man,   I'm looking now.

**Comment by drummerclint** [comment]
Arjan, is that the ltc board with the balanced io that you mentioned a while back? :o 
@hippyau little off topic but I wanted to ask you about msexlord, what's the best way to contact you?

**Comment by vanvught** [comment]
Hi Clint, 

> Arjan, is that the ltc board with the balanced io that you mentioned a while back? ⭕ 

Yes, still but still empty. However another user has made this board and successfully tested with input. 
And, quoting this user:

> I also managed to get the artnet TC really easy into Onyx :)
This looks so nice, thanks!

**Comment by drummerclint** [comment]
That's exciting!  I'm looking forward to building several.  I have some industry friends really interested in the project but don't have the electronics background to build so I may end up building a few extras for them.  I ended up writing a basic guide on getting started with just ltc output from James' beat link trigger project.  You can check it out [here](https://github.com/Deep-Symmetry/beat-link-trigger/wiki/Guide:-Building-the-Orange-Pi-LTC-SMPTE-Timecode-Reader,-Converter-&-Generator ) if you're interested.  Please let me know if you'd like me to make any changes to it.  I've been meaning to record a demo video for the longest time.  I'll let you know when that happens.

**Comment by drummerclint** [comment]
Hi Arjan, do you have the BOM for the next LTC board? 
Thanks!
Clint
