### ISSUE TITLE
Single firmware for ArtNet and sACN?

### ISSUE THREAD

**Issue by mrv96** [vanvught/rpidmx512#105]
Hi, since sACN and ArtNet are different standards that both rely on UDP, it would be possible to have a single firmware for both the standards having a setting to choose the one to use?

I ask this because many commercial and non-commercial product are like this.

Thank you.

**Comment by vanvught** [comment]
As this project is done in free time and the ease of management has the highest priority , I have chosen for separate firmware's.

Using TFTP (scripting) it is very easy to change the firmware. 

Therefore, I have no current plans for consolidating the firmware.

For reference I have attached the overview of available firmware.

Thanks, Arjan

[www.orangepi-dmx.org.pdf](https://github.com/vanvught/rpidmx512/files/4197926/www.orangepi-dmx.org.pdf)
