### ISSUE TITLE
Feature: display uptime in days/minutes/seconds

### ISSUE THREAD

**Issue by drummerclint** [vanvught/rpidmx512#108]
Currently uptime is displayed in pure seconds.  Possible to display in a more user readable format?  Not a big deal, just noticed when I wrote the other issue.

**Comment by vanvught** [comment]
This is related to the Java UI , which is provided AS-IS

cc: @rbarreiros

**Comment by vanvught** [comment]
Published -> https://github.com/vanvught/h3dmx512-zip/blob/master/RemoteConfigUI.jar?raw=true

![Schermafbeelding 2020-02-24 om 17 31 21](https://user-images.githubusercontent.com/4319913/75171394-d8c1a100-572b-11ea-83bc-dd4c67662242.png)

cc: @rbarreiros @brunchboy @hippyau
