### ISSUE TITLE
LTC SMPTE: In source selection mode with buttons: using rotary for setting Start/Stop time

### ISSUE THREAD

**Issue by vanvught** [vanvught/rpidmx512#119]
User comment:
> For LTC SMPTE. Using an encoder as described in " buttons" section, is it only for selecting the input source at startup ? Or you can set the start time when using internal generator?

Currently,  the buttons/rotary are only for the source select at startup.

cc: @hippyau @rbarreiros @brunchboy @drummerclint

**Comment by vanvught** [comment]
Please find attached the first concept. The idea:

When we are in source select and Internal is selected then press Start for changing the Start time and/or Frame rate. With pressing start we toggle between editing the Start time and Frame rate.

You can press 'Select' for activating the selected/updated Start time and/or Frame rate.
With 'Resume' you are getting out of editing mode.


cc: @hippyau @rbarreiros @brunchboy @drummerclint


[opi_emac_ltc_smpte.zip](https://github.com/vanvught/rpidmx512/files/4776647/opi_emac_ltc_smpte.zip)

**Comment by vanvught** [comment]
This is a full-functional firmware where Start, Stop and Frame-rate can be set. 

cc: @hippyau @rbarreiros @brunchboy @drummerclint

[opi_emac_ltc_smpte.zip](https://github.com/vanvught/rpidmx512/files/4805820/opi_emac_ltc_smpte.zip)

**Comment by drummerclint** [comment]
Hey Arjan, the oled display has stopped working as of this build.
After I did the tftp upload and sent a reboot command, the display showed Rebooting.. and the unit rebooted, but the display didn't change.  The 7seg changed however.

**Comment by vanvught** [comment]
Hi Clint, I did a quick test and I cannot replicate your issue. I will reopen this issue and will do some more investigation in the weekend.

**Comment by vanvught** [comment]
Working for me on two different Orange Pi Zero's.

**Comment by wyged** [comment]
Indeed. OLED Display is not working. Reverted to previous version and all ok.

**Comment by vanvught** [comment]
@wyged @drummerclint This is mostly frustrating ;-) it is all working fine for me. Do you perhaps have an USB-UART cable so I can provide a debug version and hopefully it will give us more information for what is happening.

**Comment by vanvught** [comment]
@wyged @drummerclint Two setups: With and without MCP23017. Both are working fine. I am so puzzled here. 

![IMG_3490](https://user-images.githubusercontent.com/4319913/85198184-dc82c000-b2e6-11ea-98e2-01b53fc39e95.JPG)

![Schermafbeelding 2020-06-20 om 11 11 09](https://user-images.githubusercontent.com/4319913/85198185-e3113780-b2e6-11ea-8251-6cb837baad19.png)
![Schermafbeelding 2020-06-20 om 11 11 29](https://user-images.githubusercontent.com/4319913/85198187-e5739180-b2e6-11ea-90ef-00398ae19cad.png)

**Comment by vanvught** [comment]
@wyged @drummerclint  Please find attached a debug firmware. I have added the 'i2cdetect' at startup; showing 2 MCP23017's and the SSD1306. 

[opi_emac_ltc_smpte.zip](https://github.com/vanvught/rpidmx512/files/4807695/opi_emac_ltc_smpte.zip)

![Schermafbeelding 2020-06-20 om 11 56 20](https://user-images.githubusercontent.com/4319913/85199093-53bb5280-b2ed-11ea-95b4-97841bfa845c.png)

cc: @hippyau @rbarreiros @brunchboy

**Comment by vanvught** [comment]
@wyged @drummerclint I am going out for lunch now ;)

[opi_emac_ltc_smpte.zip](https://github.com/vanvught/rpidmx512/files/4807731/opi_emac_ltc_smpte.zip)

**Comment by drummerclint** [comment]
works now :)

**Comment by vanvught** [comment]
> works now :)

Thanks Clint. 

I will adjust my test scenario's; this OLED issue shouldn't have happened.
