### ISSUE TITLE
USB HID

### ISSUE THREAD

**Issue by hippyau** [vanvught/rpidmx512#125]
Hey Arjan,

Any USB host code?  I'm particularly interested in HID devices, like keyboard or mouse?

I have seen [Some code](https://github.com/catphish/allwinner-bare-metal/blob/master/usb.c) here for the H3,  wondering what your thoughts are?

Cheers, 
  Hippy

**Comment by vanvught** [comment]
Hi Hippy,

I have had this question many times ;-)

The USB code is pretty horrible. Moreover, it will be more lines of code than I already have. I would be pretty time consuming writing, testing and maintaining the code. 

I have been looking for audio devices as well: USB audio <-> LTC. It is far more easier adding an PCM2900C. That is zero coding and just some hardware. 

Greets, Arjan

**Comment by hippyau** [comment]
Cheers Arjan,
    I was looking at the uboot USB code, similar to the linux USB stack, but yes a big pain in the ass and not worth the trouble I guess.

Hip
