### ISSUE TITLE
dmxsend: Output period too short

### ISSUE THREAD

**Issue by jelimoore** [vanvught/rpidmx512#14]
Just playing around with my Raspberry Pi Artnet to DMX (RPi 1 and QLC+ 4) node I made when I encountered this issue:

00:37:16.63 dmxsend: Output period too short (brk 92, mab 12, period 25000)

I'm using the default DMX break, mab, and refresh rate. What can I do to not make the output period too short? In QLC+ I'm using 100ms flashes which I think aren't too short. Ideally I'd like it so that either the board doesn't complain about too short of an output period, or can auto restart when it gets an output period too short error (as it doesn't work and disappears from Artnetominator when this issue occurs).

**Comment by vanvught** [comment]
The error seen is not an user error.

This is a well known issue with Raspberry Pi Model 1 R2 boards. It does not happen on all other Raspberry Pi boards. 

Please note that I am moving slowly away from the Raspberry boards and supporting the Orange Pi Zero/One boards only.

**Comment by vanvught** [comment]
Added on the main page [http://www.orangepi-dmx.org]:

> Model B(+) {Model 1 R2 has an issue with DMX output)

**Comment by vanvught** [comment]
@jelimoore Please will you confirm that there are no USB devices attached? Thanks.
I will consider implementing a 'recover' process, special for the Model 1.

**Comment by vanvught** [comment]
Trying to replicate the issue. Board: Raspberry Pi Model B R2
Using https://github.com/vanvught/rpidmx512-zip/blob/master/rpi_circle_artnet_dmx.zip?raw=true
This release includes a recent version of the Broadcom firmware.

![1r2](https://user-images.githubusercontent.com/4319913/50377272-6088b880-061a-11e9-8891-0b9ccaf18760.jpg)

**Comment by vanvught** [comment]
@jelimoore I am able to recreate the error. I am considering the recover process implementation.

![Uploading Error.jpg…]()

**Comment by jelimoore** [comment]
I don't have any USB devices attached. What's interesting now is that when I fire up QLC+, the node immediately goes into output period too short mode instead of doing stuff for a while and then erroring out.

**Comment by vanvught** [comment]
Thanks for the feedback. This is a weird issue with Raspberry Pi Model 1 R2 board. Moreover, as the Orange Pi Zero board has a far better (that is DMA controlled) Ethernet implementation, I strongly advice to switch to the 7 Euro Orange Pi Zero boards. And if you want 4x DMX/RDM out, then the Orange Pi One is the board to use. BitWizard has a 4x DMX board for the Orange Pi One. Please contact BitWizard for more information.

**Comment by jelimoore** [comment]
Thanks - I just used an old RPi1 I had laying around for this. I'll snag an orange pi zero. Will the existing DMX hat for my raspberry work with the Orange pi zero? I assume the pinouts of the GPIO header are similar but want confirmation that is the case.

**Comment by vanvught** [comment]
`Will the existing DMX hat for my raspberry work with the Orange pi zero?`
Yes, but the board will be outside the Opi. 

![index](https://user-images.githubusercontent.com/4319913/50378166-ad28bf80-062b-11e9-8ddc-9fa90382367f.jpg)

**Comment by vanvught** [comment]
@jelimoore The attached kernel has a warning message instead of the panic message. Applies for Model 1 only. 

[kernel.zip](https://github.com/vanvught/rpidmx512/files/2705495/kernel.zip)

**Comment by jelimoore** [comment]
Thanks, you've gone above and beyond for some internet stranger, closing
