### ISSUE TITLE
OPi Zero GPIO to HUB-75 

### ISSUE THREAD

**Issue by hippyau** [vanvught/rpidmx512#149]
![image](https://user-images.githubusercontent.com/36442309/95445663-97bc8b00-09a2-11eb-83ee-737b17cacfce.png)

Can the OrangePi can drive these pins directly without level shifting hardware?

Cheers :)

**Comment by vanvught** [comment]
> Can the OrangePi can drive these pins directly with level shifting hardware?

Yes, it can. However, I am planning to design an open source hardware board for the OPi Zero with 2x 74HCT245.
I am going to save that image. Dank :)

**Comment by hippyau** [comment]
I've pulled and compiled latest experimental ltc firmware,

Should I only need to add `rgbpanel_enable=1` to ltc.txt ?

:)

**Comment by vanvught** [comment]
> Should I only need to add rgbpanel_enable=1 to ltc.txt ?
Yes

The sources can only be the network protocols or systime. 

And please add: `if (tLtcDisabledOutputs.bRgbPanel)  ....`

```
		if ((!tLtcDisabledOutputs.bWS28xx) || (!tLtcDisabledOutputs.bRgbPanel)) {
			ltcDisplayRgb.Run();
		}

		if (tLtcDisabledOutputs.bRgbPanel) {
			lb.Run();
		}
```

And remove this line -> https://github.com/vanvught/rpidmx512/blob/experimental/opi_emac_ltc_smpte/firmware/main.cpp#L547

![Schermafbeelding 2020-10-08 om 16 37 26](https://user-images.githubusercontent.com/4319913/95474047-fa069300-0984-11eb-895a-5bda342f2f7d.png)

**Comment by hippyau** [comment]
Thanks so much for the info...
  
I kill a OPi maybe :)  I think either it was bad from the factory (never used before), or I wired my ribbon cable up wrong because I was eager to see it in action.  I just get nothing on the UART0 from it at all, no uboot... it's dead :(   

All my others are hooked up to stuff, so I'm going to order some Zeros now.   :) 

I was in such a rush, I used the IDC cable that came with the panel, it is not copper but aluminum wire :( and didn't solder well... but this didn't kill the OPi.    

How many panels in full resolution do you think the OPi can generate at ~30FPS?  Since I don't think we could handle more than 2 or 3 panel max (?), I was thinking of making (when time) a pcb that adapts the HUB-75 directly to the OPi header,  so was small PCB that holds OPi here.  

![20201010_002907](https://user-images.githubusercontent.com/36442309/95596950-61116e00-0a91-11eb-818e-0ff8215b68b1.jpg)

**Comment by vanvught** [comment]
> How many panels in full resolution do you think the OPi can generate at ~30FPS?

The FPS depends on the colour depth. With the current setting there is 120FPS for 64x32 led panel.

**Comment by vanvught** [comment]
Hi Hip,

When you install https://github.com/vanvught/rpidmx512/tree/experimental/scratch-h3-matrix_gpio then the OLED display will show both the panel FPS and the sACN E1.31 FPS.
The colour depth is set here -> https://github.com/vanvught/rpidmx512/blob/experimental/lib-rgbpanel/include/rgbpanel.h#L35

**Comment by hippyau** [comment]
Hey Arjan!! 

I have an Zero all hooked up, I used fresh pull of the above scratch-h3-matrix_gpio, but I am not sure my ACN setup is working...  I can see on scope on the clock line it's working, but no pixels on display,  I think my DMX is not getting there...

So just wanting to test rgb panel is working, I have not seen any pixels yet, so decide to try ltc firmware, but fresh pull from experimental, and I can't get opi_emac_ltc_smpte compile...

I can see lib-midi get compiled, but later I get an RtpMidiHandler problem?

```
$TARGET [lib_h3/libh3.a ]
arm-none-eabi-ar: creating lib_h3/libh3.a
[/mnt/d5e5c544-a90f-45fd-b1b3-d028b0ebdd07/OrangePi/rgbpanel/rpidmx512/lib-arm]
[src src/h3  src/debug]
$DEFINES [-DORANGE_PI  -DNDEBUG -D_TIME_STAMP_YEAR_=2020 -D_TIME_STAMP_MONTH_=11 -D_TIME_STAMP_DAY_=6 -DREMOTE_CONFIG]
$MAKE_FLAGS [-DLTC_READER -DRDMNET_LLRP_ONLY -DARM_ALLOW_MULTI_CORE -DNDEBUG -DENABLE_TC1602 -DENABLE_CURSOR_MODE -D_TIME_STAMP_YEAR_=2020 -D_TIME_STAMP_MONTH_=11 -D_TIME_STAMP_DAY_=6]
$BUILD_DIRS [build_h3/src build_h3/src/h3 build_h3/src/debug]
$TARGET [lib_h3/libarm.a ]
arm-none-eabi-ar: creating lib_h3/libarm.a
../lib-ltc/lib_h3/libltc.a(rtpmidireader.o): In function `RtpMidiReader::~RtpMidiReader()':
rtpmidireader.cpp:(.text+0x44): undefined reference to `RtpMidiHandler::~RtpMidiHandler()'
../lib-ltc/lib_h3/libltc.a(rtpmidireader.o): In function `RtpMidiReader::~RtpMidiReader()':
rtpmidireader.cpp:(.text+0x74): undefined reference to `RtpMidiHandler::~RtpMidiHandler()'
../h3-firmware-template/Rules.mk:223: recipe for target 'build_h3/main.elf' failed
make: *** [build_h3/main.elf] Error 1
hip@hip-Alienware-13:~/OrangePi/rgbpanel/rpidmx512/opi_emac_ltc_smpte$

```

Any ideas?

**Comment by hippyau** [comment]
additionally, using the scratch-h3-matrix_gpio firmware, in the RC manager, I only get two files...
![image](https://user-images.githubusercontent.com/36442309/98367912-272c8b00-2082-11eb-9418-4fa2d33e8f91.png)

I'm using qlcplus and sending unicast, but can't tell if my DMX is getting there...

```
Shell() lib/h3/shell.cpp, line 74: TABLE_SIZE=14
MX25L1605D, sector size 4096, 2097152 bytes
Detected MX25L1605D with sector size 4096 total 2097152 bytes
[V0.0] Orange Pi Zero Compiled on Nov  6 2020 at 21:42:54
Network
 Hostname  : allwinner_380453
 If        : 1: eth0
 Inet      : 192.168.1.134/24
 Netmask   : 255.255.255.0
 Gateway   : 192.168.1.1
 Broadcast : 192.168.1.255
 Mac       : 02:42:04:38:04:53
 Mode      : D
PlatformInit() src/h3/rgbpanel.cpp, line 128: nBufferSize=172032
PlatformInit() src/h3/rgbpanel.cpp, line 136: 0x4050082c 0x405a883c
smp_start_core(1, core1_task)
Running
RGB led panel
 64x32x1
 Universes : 1 to 13-24
Bridge
 Firmware : 1.19
 Output
  Port  0 Universe 1   [HTP]
  Port  1 Universe 2   [HTP]
  Port  2 Universe 3   [HTP]
  Port  3 Universe 4   [HTP]
  Port  4 Universe 5   [HTP]
  Port  5 Universe 6   [HTP]
  Port  6 Universe 7   [HTP]
  Port  7 Universe 8   [HTP]
  Port  8 Universe 9   [HTP]
  Port  9 Universe 10  [HTP]
  Port 10 Universe 11  [HTP]
  Port 11 Universe 12  [HTP]
  Port 12 Universe 13  [HTP]
 Direct update : Yes

```

**Comment by hippyau** [comment]
Update:  I can see R G B, Latch, OE signals on the scope, i'm confident something should be happening, maybe my panel not working :(

**Comment by vanvught** [comment]
![Schermafbeelding 2020-11-06 om 14 01 33](https://user-images.githubusercontent.com/4319913/98369122-bb720000-2038-11eb-8841-304cdfbb5ede.png)
![Schermafbeelding 2020-11-06 om 14 02 12](https://user-images.githubusercontent.com/4319913/98369139-bdd45a00-2038-11eb-91c8-bef81b0d9bba.png)



![IMG_3664](https://user-images.githubusercontent.com/4319913/98368957-71891a00-2038-11eb-8ba8-a1c1e93a1e5f.png)

**Comment by vanvught** [comment]
> additionally, using the scratch-h3-matrix_gpio firmware, in the RC manager, I only get two files...

That's 'fixed' in the latest commit -> https://github.com/vanvught/rpidmx512/blob/experimental/scratch-h3-matrix_gpio/firmware/main.cpp#L126

**Comment by hippyau** [comment]
Dank!  I will try now :)

**Comment by hippyau** [comment]
Hey Arjan, getting closer, but now...

```
[src src/h3  src/debug]
$DEFINES [-DORANGE_PI  -DNDEBUG -D_TIME_STAMP_YEAR_=2020 -D_TIME_STAMP_MONTH_=11 -D_TIME_STAMP_DAY_=6 -DREMOTE_CONFIG]
$MAKE_FLAGS [-DLTC_READER -DRDMNET_LLRP_ONLY -DARM_ALLOW_MULTI_CORE -DNDEBUG -DENABLE_SSD1311 -DENABLE_TC1602 -DENABLE_CURSOR_MODE -D_TIME_STAMP_YEAR_=2020 -D_TIME_STAMP_MONTH_=11 -D_TIME_STAMP_DAY_=6]
$BUILD_DIRS [build_h3/src build_h3/src/h3 build_h3/src/debug]
$TARGET [lib_h3/libdisplay.a ]
src/lcdbw.cpp: In member function 'void LcdBw::Write(const char*, uint32_t)':
src/lcdbw.cpp:161:27: error: 'micros' was not declared in this scope
  161 |  const uint32_t elapsed = micros() - m_nWriteMicros;
      |                           ^~~~~~
../h3-firmware-template/lib/Rules.mk:114: recipe for target 'build_h3/src/lcdbw.o' failed

```

**Comment by hippyau** [comment]
is to do with `-DENABLE_SSD1311 -DENABLE_TC1602` ? ... I don't have those devices, where to disable?

**Comment by vanvught** [comment]
> is to do with -DENABLE_SSD1311 -DENABLE_TC1602 ? ... I don't have those devices, where to disable?

It has nothing to do with the defines. And they should not be disabled.

**Comment by hippyau** [comment]
I had a wiring problem :)  I now have some pixel action...  but still can't compile because of above.

**Comment by vanvught** [comment]
```
src/lcdbw.cpp: In member function 'void LcdBw::Write(const char*, uint32_t)':
src/lcdbw.cpp:161:27: error: 'micros' was not declared in this scope
  161 |  const uint32_t elapsed = micros() - m_nWriteMicros;
      |                           ^~~~~~
../h3-firmware-template/lib/Rules.mk:114: recipe for target 'build_h3/src/lcdbw.o' failed
```

I was able to reproduce this error. I have committed files in order to fix the issue. I cloned 'experimental' to a different place and the compilation is running fine now.

**Comment by hippyau** [comment]
I didn't see commit, will try now... :)

**Comment by hippyau** [comment]
Compiles :+1:  :+1:  :+1:

**Comment by vanvught** [comment]
>  I now have some pixel action...

You can change the color depth here -> https://github.com/vanvught/rpidmx512/blob/experimental/lib-rgbpanel/include/rgbpanel.h#L35
The OLED display will tell the refresh rate of the panel.

**Comment by hippyau** [comment]
Yay, thanks!!!!!!!!!!!!

![20201106_235245](https://user-images.githubusercontent.com/36442309/98373702-63b0b480-208b-11eb-92bd-2bc283cf6332.jpg)

**Comment by vanvught** [comment]
The last colon dot will be fixed soon :-)

When you still awake, can you check the clock frequency of the panel CLK?

It is on my todo list, but you have the scope ready 😀

**Comment by hippyau** [comment]
Hey Arjan,  
 This is straight off PA10,  it drops a clock every now and then, but seems pretty consistently about 9MHz...

![screenshot](https://user-images.githubusercontent.com/36442309/98376057-b5a70980-208e-11eb-94ba-a58b3c876fd5.png)

**Comment by hippyau** [comment]
Hey Arjan,  I have this other small panel...

![20201107_000030(1)](https://user-images.githubusercontent.com/36442309/98376542-61505980-208f-11eb-9d63-1442c654ac2d.jpg)

It seems to have a colour swap?  See the yellow is blue?  This wiring is the same, I have glued together dupont wires into a connector,  works as expected on big panel, but different on the small panel... 

[P2.5 Indoor Full Color LED Display Module HUB75,160mm x80mm, 64*32 Pixels,SMD RGB P2.5 LED Panel Matrix, Compatible With PIN2DMD](https://a.aliexpress.com/_mO2eMVx)

**Comment by vanvught** [comment]
> This is straight off PA10, it drops a clock every now and then, but seems pretty consistently about 10MHz...

Hi Hip, thanks! 

When there is a drop, then the row address is being latched. 
The 10Mhz is what I thought it would be based on refresh rate and color depth. It relatively low frequency; I am not sure yet if this is a limitation for the Allwinner H2+/H3 SoC, or that there is lock in my multi-core code preventing higher frequency.

For the sACN firmware where we can select the panel size and and panel count, we can use this 10 MHz for setting the color depth with having around 120 FPS panel update.

**Comment by vanvught** [comment]
> It seems to have a colour swap? See the yellow is blue? This wiring is the same, ...

I have ordered 3 another display's from the same seller; I really hope that the color scheme is the same for all 4. I am intending to make 2x2 64x32 display .... ;-)

**Comment by vanvught** [comment]
![IMG_3662](https://user-images.githubusercontent.com/4319913/98383175-70fa7e80-204c-11eb-80df-f5e218008ee2.jpeg)
https://github.com/vanvught/h3dmx512-zip/tree/master/eagle/Orange-Pi-Zero/RGB-panel

**Comment by hippyau** [comment]
Hey, do you happen to know if JLCPCB has these components in it's assembly option?

**Comment by vanvught** [comment]
> Hey, do you happen to know if JLCPCB has these components in it's assembly option?

Yes, they have. The BOM and placement file is on my GitHub. Just upload, click , click ... pay and ready ;-)

**Comment by hippyau** [comment]
<3 <3 Thanks!  I'm doing it now :)

**Comment by hippyau** [comment]
Hey Arjan,
  Trying to now test the scratch-h3-matrix_gpio firmware,  but I can no longer see the opi in the remote config util, but it's online.  

it's being seen in scan, `192.168.1.134,sACN E1.31,RGB Panel,13` but giving an `Invalid respone` ?

remote config util console output:
```
hip@hip-Alienware-13:~/OrangePi$ ./run.sh
Linux
enp2s0
	/fe80:0:0:0:f10f:a22d:2bf7:9a73%enp2s0 false false false
	/192.168.1.49 false false false
Local ip: 192.168.1.49
Interface address: 192.168.1.49
192.168.1.56,LTC,TimeCode,7,BigTC
Mode[0]=TimeCode
{192.168.1.56 LTC TimeCode 7} {BigTC}
192.168.1.134,sACN E1.31,RGB Panel,13
Mode[0]=RGB Panel
Invalid respone
No more messages.

```

**Comment by hippyau** [comment]
Hi Arjan,

sACN is working great, I've got smooth pixel mapping...
![2020-11-07_17_47_51](https://user-images.githubusercontent.com/36442309/98435830-0f0c4880-2122-11eb-839d-cc19f48e7529.gif)

I did notice if the sACN stream stops then starts again a bit later,  I get another `smp_start_core(1, core1_task)` message on the console and it crashes and needs hard power cycle, WDT not kicking in.    Otherwise it's been running for an hour and hasn't missed a beat!

**Comment by vanvught** [comment]
Hi Hippy,

> did notice if the sACN stream stops then starts again a bit later, I get another smp_start_core(1, core1_task) message on the console and it crashes and needs hard power cycle

Yes, the 'blackout' feature is not working, yet. 

> WDT not kicking in. 

Yes, there is no WDT; that makes debugging easier.

**Comment by hippyau** [comment]
Very happy, thanks Arjan!!    Side note, I can run this free pixel matrix software in Linux under WINE perfectly.... [Jinx!](http://www.live-leds.de/)

**Comment by hippyau** [comment]
> It seems to have a colour swap? See the yellow is blue? This wiring is the same, I have glued together dupont wires into a connector, works as expected on big panel, but different on the small panel...
> 
> [P2.5 Indoor Full Color LED Display Module HUB75,160mm x80mm, 64*32 Pixels,SMD RGB P2.5 LED Panel Matrix, Compatible With PIN2DMD](https://a.aliexpress.com/_mO2eMVx)

Confirming this panel has green and blue swapped - it's RBG

**Comment by hippyau** [comment]
oPi Zero only hits 41 degrees Celsius when running two cores and receiving 13 sACN universes.  This is good, because in Australia it hits 40 in summer,  put it in a closed black box in the sun, will still probably keep running :)  I'll test on Christmas Day, hehehe...
 
![image](https://user-images.githubusercontent.com/36442309/98438094-7252a680-2133-11eb-9a5d-1bd1166260b8.png)

**Comment by hippyau** [comment]
> The FPS depends on the colour depth. With the current setting there is 120FPS for 64x32 led panel.

Does overall brightness also relate to colour depth?  My tiny 2.5P panel is not very bright.

**Comment by vanvught** [comment]
Hi Hippy,

> Trying to now test the scratch-h3-matrix_gpio firmware, but I can no longer see the opi in the remote config util, but it's online.

Are you using the latest code ?

![Schermafbeelding 2020-11-07 om 11 05 24](https://user-images.githubusercontent.com/4319913/98438248-401c5700-20e9-11eb-85b4-996d81384443.png)

**Comment by hippyau** [comment]
I'm using the latest RemoteConfig jar I could find, which is from August in the GPS thread.  
I compiled the firmware today.

**Comment by vanvught** [comment]
> Does overall brightness also relate to colour depth? My tiny 2.5P panel is not very bright.

The RGB DMX values 0xFF, 0xFF, 0xFF are always translated to a full-on for all led's

**Comment by vanvught** [comment]
> I'm using the latest RemoteConfig jar I could find, which is from August in the GPS thread.

I have not updated the .jar. There is updates sources only ;-)

Give me a second ...

**Comment by vanvught** [comment]
[Uploading RemoteConfigUI.jar.zip…]()

**Comment by vanvught** [comment]
[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/5504559/RemoteConfigUI.jar.zip)

**Comment by hippyau** [comment]
Thank you, I can see it now :+1:   :) 
![image](https://user-images.githubusercontent.com/36442309/98438429-ceb6c580-2135-11eb-8b00-d501f9adebbd.png)

**Comment by vanvught** [comment]
Thank you Hippy!!

When you would like to see 'strange' things happening; put a full 13 Universe image on the panel. Stop outputting, wait for the timeout, the blackout. And then send Universe 13 (or the last Universe) only .. :-)

**Comment by hippyau** [comment]
I'm trying to hack in a 5x8 font, but not really winning.  I can see I need to >> 3 to get to the 5 bits, but just getting gobbly gook.   Work in progress,  you might see at a glance where i'm going wrong.   Plus, keep in mind I'll clean up once it's working :) 

[ Trying to hack in a 5x8 font... WIP](https://github.com/hippyau/rpidmx512/commit/a9b76953fbcbe4c49c4ac994a804d488488a75f9)

**Comment by hippyau** [comment]
Yay, my boards arrived!   Just FYI,  JLC warned me that U1 and U2 placing was possibly an issue.  I said build anyway, and they look great.     One question:  is the +5v an output?

![image](https://user-images.githubusercontent.com/36442309/99392083-e0168380-2926-11eb-9e1c-af91565a1bc8.png)

**Comment by vanvught** [comment]
> One question: is the +5v an output?

No, that is input. Back powering the Orange Pi Zero on the header based on the recommendation for a Raspberry Pi HAT

**Comment by rewolff** [comment]
.... But in practise if you have  good reason, you could also power the orange pi itself. That would make this connector either unnecessary or an output. But keep in mind that the reason of that rpi recommendation is that you might have a fuse on the "xxx-pi" board, so that you can trigger that fuse if you draw too much.
So best is to follow the recommendations and power everything properly fused from the hat.

**Comment by vanvught** [comment]
I am using these boards for debugging and testing my firmware and make it open source hardware (https://github.com/vanvught/h3dmx512-zip/tree/master/eagle/Orange-Pi-Zero/RGB-panel), therefore if someone has its own requirements, they can simply change the board.

**Comment by hippyau** [comment]
Hey Arjan!  

I got my boards in the mail :)   Thanks so much for creating this board!!  I've built up one with OLED display too...

![20201118_224231](https://user-images.githubusercontent.com/36442309/99532346-dad13b80-29ef-11eb-9c8d-8ea00ee333c9.jpg)

It's awesome!  I do have a tiny hick-up,  I have a bit of small flicker.  

I hooked up the scope to the clock lines and they look pretty much the same.

The only thing 'major' besides the whole hat itself, that is different between my two test units is the OLED display.   Same configs, same firmware - one is wired direct to the panel, one has a hat + oled.   

foolishly I solder the OLED on, is there a config to force disable it? I presume the OLED is detected and only used when connected?    

Have you seen a slight flicker?

Not stressed at all, direct connect works great, **love it :)** 


![image](https://user-images.githubusercontent.com/36442309/99533028-f12bc700-29f0-11eb-8e3d-01847213a57f.png)
(hat)

![image](https://user-images.githubusercontent.com/36442309/99533176-3223db80-29f1-11eb-95ee-bd9df7a2fa2e.png)
(direct)

**Comment by hippyau** [comment]
I've looked at the data-sheet and I am kind of sure these are the same, kind of? 
![image](https://user-images.githubusercontent.com/36442309/99534426-1d484780-29f3-11eb-98b4-3b06d4261b56.png)
(My part left, your part Right)

**Comment by vanvught** [comment]
Hi Hippy,

> foolishly I solder the OLED on, is there a config to force disable it? I presume the OLED is detected and only used when connected?

Yes, when a supported OLED is detected, then it is used.

> Have you seen a slight flicker?

I have a major backlog for things to do (most time consuming is #152, I am in direct contact with the company, but so little support; I cannot get the OLED to work) and so little free time; I still have to solder the boards ;-)

For the 245, I would expect to see AHCT, the fast version. But as your scope is showing fine signals, it would be ok.
I really do hope that I can find some time in the weekend for building one board. 

But there is also still this empty page -> http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/ws28xx-configuration/prototype-boards/multi/8-output ;-(

> Not stressed at all, direct connect works great, love it :)

:-)

**Comment by hippyau** [comment]
Thanks man...  I just built another board without OLED and have no flicker :) the hardware works great!!  <3

I'll have a look and see if I can halve the update speed of the OLED maybe and that will probs solve it.   not a big problem :)

> and so little free time; I still have to solder the boards ;-)

I am still to assemble my LTC boards - i've had all the parts for over a month now hehe!   

Very happy with the support!  Stay well and sane, don't worry about me, I get there eventually :) just like to document my journey!

**Comment by hippyau** [comment]
[observation] Very interesting... board with OLED still fickers when display on or off, using the gui to toggle, the OLED display does blank when off, but the display still flickers.  The new board without any OLED display is with no visible flicker.  

![image](https://user-images.githubusercontent.com/36442309/99544956-9b5f1b00-2a00-11eb-9b3b-cea57f6963b9.png)

**Comment by vanvught** [comment]
> board with OLED still fickers when display on or off,

When the OLED display is off, then there is still I2C activity. The I2C on the header is also GPIOA, which is controlling the panel. So, it might be a good idea not outputting the Timecode to OLED when this panel is active. And just showing the static information on the OLED.

Fact; in my current setup there is no OLED connected and there is no flickering ....

**Comment by hippyau** [comment]
Thanks, i've made a hack for above UI contol,  when display is off... display is not updated.   Works for my board with OLED display.     No stress :1st_place_medal:

**Comment by hippyau** [comment]
Show message blocks TC somehow... lol, is my code no doubt! 
[unlisted youtube video showing issue]( https://youtu.be/1nxXxa8Fqh0 )
