### ISSUE TITLE
RemoteConfigUI - firmware update workflow and backup/restore

### ISSUE THREAD

**Issue by hippyau** [vanvught/rpidmx512#156]
To update firmware, follow this procedure:

1.  Open Remote Config UI  ->  `$ java -jar RemoteConfigUI.jar`
2.  Select target device from list
3.  Using menus, `Action -> TFTP On/Off`,  confirm On.
4.  Using menus, `Run -> TFTP Client`
5.  Use "`Select uImage`" button to select the firmware to upload
6.  Use "`TFTP put`" button to upload firmware
7.  If success, text will turn green.
8.  Using menus, `Action -> TFTP On/Off`, confirm Off (firmware is now written to SPI flash)
9.  Right click on device, or use menus Action -> Reboot to start the new firmware.

It'd be awesome if the TFTP client would turn on TFTP and then turn off after upload, then reboot, so the firmware is update is one operation.  If we forget one step, it can leave beginners scratching their heads. 

I get the TFTP client might get used for other files in the future, so maybe a separate firmware update routine would be good.

**Comment by vanvught** [comment]
For reference, the steps described is exactly the flow as used when automating using scripting -> https://github.com/vanvught/h3dmx512-zip/blob/master/do-tftp.sh

**Comment by hippyau** [comment]
Annoying for you and me maybe, but RemoteConfigUI not allow reuse port of remote config messages, and do-tftp.sh fails when RC is open, because netcat faults on binding `nc: bind failed: Address already in use` presumably when trying to enable TFTP.   

Low priority.

**Comment by vanvught** [comment]
>  Annoying for you ...

Well not really, the RemoteConfigUI is an AS-IS application demonstrating the remote configuration framework. I do my build workflow completely from the command-line.

**Comment by hippyau** [comment]
Understood,  if I knew how to compile it, I could have a crack at it.   Pretty sure setsocketopt with SO_REUSEADDR would do the trick.  I do compile and do-tftp on the command line, but editing the .txt files is so much easier with the UI :)

**Comment by vanvught** [comment]
> netcat faults on binding nc: bind failed: Address already in use

It seems to me that `netcat` is not doing the re-use

**Comment by vanvught** [comment]
It is set in my code -> https://github.com/vanvught/rpidmx512/blob/master/RemoteConfigUI/src/org/orangepi/dmx/RemoteConfig.java#L893

**Comment by hippyau** [comment]
ahh, okay thanks... doh!   never mind, sorry to waste your time.  `netcat` might require recompile to accomplish [https://superuser.com/questions/1321883/how-to-make-nc-listen-on-a-port-without-setting-so-reuseport](https://superuser.com/questions/1321883/how-to-make-nc-listen-on-a-port-without-setting-so-reuseport).

**Comment by vanvught** [comment]
-> [http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/example-java-ui/workflow-firmware-installation](http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/example-java-ui/workflow-firmware-installation)

**Comment by vanvught** [comment]
New Menu Item

![Schermafbeelding 2020-11-15 om 18 05 45](https://user-images.githubusercontent.com/4319913/99191504-625b4800-276d-11eb-9b52-a355b1b080c3.png)

After TFTP On, the TFTP Client is shown

![Schermafbeelding 2020-11-15 om 18 06 10](https://user-images.githubusercontent.com/4319913/99191513-7010cd80-276d-11eb-92a4-76525230a86c.png)

After finishing the TFTP transfer, there is a TFTP Off and the Reboot

![Schermafbeelding 2020-11-15 om 18 06 20](https://user-images.githubusercontent.com/4319913/99191533-861e8e00-276d-11eb-83ed-2ec38771f77b.png)

and waiting for the Node to be back and showing the (new) firmware version

![Schermafbeelding 2020-11-15 om 18 06 35](https://user-images.githubusercontent.com/4319913/99191562-ae0df180-276d-11eb-98eb-f562838768f3.png)

**Comment by vanvught** [comment]
[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/5542787/RemoteConfigUI.jar.zip)

**Comment by drummerclint** [comment]
This is awesome!

**Comment by vanvught** [comment]
@drummerclint 
> This is awesome!

Thanks! We are close to perfection.

**Comment by hippyau** [comment]
Look at all the work you have done!  👏🏻
![image](https://user-images.githubusercontent.com/36442309/99542200-7fa64580-29fd-11eb-835f-c425108c1a08.png)

**Comment by drummerclint** [comment]
> @drummerclint
> 
> > This is awesome!
> 
> Thanks! We are close to perfection.

Indeed!  Can we have an option to download/backup a config from an opi to load onto another?

**Comment by vanvught** [comment]
@drummerclint 
> Can we have an option to download/backup a config from an opi to load onto another?

Yes, we can :-) I need to fix some details. 

[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/5568936/RemoteConfigUI.jar.zip)


![Schermafbeelding 2020-11-19 om 19 28 42](https://user-images.githubusercontent.com/4319913/99708233-dfecc400-2a9d-11eb-9be8-117b2f9d5ddb.png)
![Schermafbeelding 2020-11-19 om 19 29 06](https://user-images.githubusercontent.com/4319913/99708237-e24f1e00-2a9d-11eb-89aa-beddd3e18682.png)
![Schermafbeelding 2020-11-19 om 19 29 37](https://user-images.githubusercontent.com/4319913/99708238-e24f1e00-2a9d-11eb-9f8f-a5e790651f12.png)
![Schermafbeelding 2020-11-19 om 19 30 09](https://user-images.githubusercontent.com/4319913/99708239-e2e7b480-2a9d-11eb-8de2-5c28fa6cccf2.png)
![Schermafbeelding 2020-11-19 om 19 30 30](https://user-images.githubusercontent.com/4319913/99708242-e3804b00-2a9d-11eb-859f-06375dfdf56d.png)
