### ISSUE TITLE
LTC SMPTE:  Add support for MIDI Clock (BPM) view and generation 

### ISSUE THREAD

**Issue by vanvught** [vanvught/rpidmx512#166]
- When the source is MIDI or the source is rtpMIDI then show the BPM (MIDI Clock). 
- When the source is not MIDI and the source is not rtpMIDI, then make it possible to generate MIDI Clock.
- The MIDI System Realtime commands Clock, Start, Stop and Continue are controlled by means of plain text UDP and OSC commands.

cc: @hippyau @rbarreiros @brunchboy @wyged @drummerclint @ferrandis87

**Comment by brunchboy** [comment]
Nice, I will point people at this when they want a way to generate MIDI clock from Pioneer DJ equipment.

**Comment by vanvught** [comment]
> Nice, I will point people at this when they want a way to generate MIDI clock from Pioneer DJ equipment.

We can also look at TCNet data packets. There is the BPM value available and then we can use this value for generating the MIDI clock automatically.

**Comment by vanvught** [comment]
[orangepi_zero.uImage.gz](https://github.com/vanvught/rpidmx512/files/5735090/orangepi_zero.uImage.gz)

[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/5735089/RemoteConfigUI.jar.zip)
![Schermafbeelding 2020-12-23 om 12 42 14](https://user-images.githubusercontent.com/4319913/102995709-ec8f8c80-4521-11eb-90b9-b00bf927bbb4.png)
![Schermafbeelding 2020-12-23 om 12 42 36](https://user-images.githubusercontent.com/4319913/102995719-ef8a7d00-4521-11eb-90cd-569d1cd7c1f9.png)
