### ISSUE TITLE
LTC SMPTE: Add Toggle/Field for Unicast ArtNet Timecode Address

### ISSUE THREAD

**Issue by lmcncola** [vanvught/rpidmx512#177]
Having a Unicast option for Artnet Timecode output would be useful in setups with multiple devices. The control should be in ltc.txt

**Comment by vanvught** [comment]
[orangepi_zero.uImage.gz](https://github.com/vanvught/rpidmx512/files/6117803/orangepi_zero.uImage.gz)


cc: @hippyau @rbarreiros @brunchboy @wyged @drummerclint @ferrandis87

**Comment by lmcncola** [comment]
Thank you!  Can’t wait to try it out tomorrow. 

Cheers!

Mike C

Mike Cianciola
Production Services
414.581.5233-mobile
***@***.***




On Mar 10, 2021, at 1:16 PM, Arjan ***@***.***> wrote:

﻿
orangepi_zero.uImage.gz

cc: @hippyau @rbarreiros @brunchboy @wyged @drummerclint @ferrandis87
