### ISSUE TITLE
how to make it work guide

### ISSUE THREAD

**Issue by pete111** [vanvught/rpidmx512#178]
Hi, 
I bought this board http://bitwizard.nl/shop/DMX-interface-for-Raspberry-pi-with-usb-(FT245RL)
I have Raspberry Pi 4 with latest Raspberry Pi OS installed. 

But I am lost on how to make this dmx board working with Raspberry Pi 4 (which commands to run, what to install, software, jumpers, wires, etc.). I did not find step by step guide for this. I just found zip file with kernel.img, kernel7.img, and similar files but there is no instruction what to do with it when I have already installed Raspberry OS.
I also found this site https://sites.google.com/site/rpidmx512/archive/raspberry-pi-dmx512-rdm but there are no easy instructions for this hat board. 

P.S. I need to use it for simple sending channel values to my DMX light with Python programming language, so sample would be highly appreciated.

Can you please help me how to make it working with RPi4?

**Comment by vanvught** [comment]
The USB board [http://bitwizard.nl/shop/DMX-interface-for-Raspberry-pi-with-usb-(FT245RL)](http://bitwizard.nl/shop/DMX-interface-for-Raspberry-pi-with-usb-(FT245RL)) is originally designed for the Raspberry Pi Zero. 

The description for the USB board use here -> [http://www.orangepi-dmx.org/raspberry-pi-rdm-controller](http://www.orangepi-dmx.org/raspberry-pi-rdm-controller)

Please be aware that I've moved away from the Raspberry Pi boards -> [https://github.com/vanvught/rpidmx512-zip/issues/6#issuecomment-640098142](https://github.com/vanvught/rpidmx512-zip/issues/6#issuecomment-640098142)
