### ISSUE TITLE
Network: DHCP Client

### ISSUE THREAD

**Issue by vanvught** [vanvught/rpidmx512#179]
Follow-up for https://github.com/vanvught/rpidmx512/issues/151#issuecomment-794105766
> > > Does firmware look once and once only for network?
> > 
> > 
> > Yes. Just at startup.
> 
> Hello Arjan,
> 
> Perhaps this should be changed? We have some environments where the DHCP is out of our control (and is quite slow to boot). So I could imagine that e.g. after a power surge the Orange Pi's would boot - fail to acquire a DHCP lease and be stuck with their locally assigned IP. Obviously this is not desirable. Attempting DHCP renewal or rebooting (if board has local IP) at X interval would be great for this (X perhaps even configurable) :-)
> 
> Best regards,
> Søren

cc: @soerenpedersen

**Comment by vanvught** [comment]
Value in minutes between 0 and 5. Where 0 is no retry.

![Schermafbeelding 2021-03-10 om 18 25 10](https://user-images.githubusercontent.com/4319913/110670993-4ec96680-81ce-11eb-81fe-8d499d88b7b4.png)

cc: @soerenpedersen

**Comment by soerenpedersen** [comment]
Looks good! Looking forward to testing it out :-)

**Comment by vanvught** [comment]
@soerenpedersen Hi Søren, herewith test firmware.

[orangepi_zero.uImage.gz](https://github.com/vanvught/rpidmx512/files/6118554/orangepi_zero.uImage.gz)

**Comment by hippyau** [comment]
Can the MAC detect link up/down?

**Comment by hippyau** [comment]
Thanks, I was more thinking a link-goes-up event could triggers the DHCP
client.

**Comment by vanvught** [comment]
The case for DHCP client retry is when there is a ink-up, but the DHCP is not reachable/available, yet.

**Comment by vanvught** [comment]
> Perhaps it should be enabled by default when DHCP is configured?

That would break the IP Addressing Modes as described here -> https://github.com/vanvught/rpidmx512/issues/117#issuecomment-630290528

**Comment by hippyau** [comment]
> then defaulting to the 2.x.y.z (based on MAC address as specified in Art-Net 4 "IP address configuration – Static Addressing").

I suggest is bad practice,  2.x.x.x is an internet route-able IP range,  feel sorry for the people on it :)   Should use 10.x,x,x /wherever possible/.

**Comment by vanvught** [comment]
> I suggest is bad practice, 2.x.x.x is an internet route-able IP range, feel sorry for the people on it :) Should use 10.x,x,x /wherever possible/.

2.x.x.x is part of the Art-Net standard. And all my firmware is 100% compliant with any standards used in the lighting industry.

**Comment by hippyau** [comment]
Understood,  but they also support 10.x.x.x and this complies with a
preceding network RFC-5735.   in my eyes btw! I don't really care.... not
your problem.... just saying :)
Hope you are well :)

**Comment by soerenpedersen** [comment]
> > Perhaps it should be enabled by default when DHCP is configured?
> 
> That would break the IP Addressing Modes as described here -> [#117 (comment)](https://github.com/vanvught/rpidmx512/issues/117#issuecomment-630290528)

Ah, I see. Looking forward to testing out your firmware some more when my RJ45 connectors finally arrive for the 8x 4 board. :-)

**Comment by vanvught** [comment]
>  8x 4 board. :-)

Cool! With feedback from other users I have made some great updates to the 8x 4U firmware. I hope to publish it this weekend.

I am also working on an simpler board with the 5M80ZE64C5N CPLD. The BOM is € 6,04

![zero_board](https://user-images.githubusercontent.com/4319913/110854674-97a81a80-82b5-11eb-81e2-50715b98ea83.png)
