### ISSUE TITLE
RGB Panel: Some weird flickering not present previously

### ISSUE THREAD

**Issue by hippyau** [vanvught/rpidmx512#194]
Hi Arjan,

I notice some ghost pixels in the latest version that were not present in the firmware I was previously using (Version 2.8 compiled November 12 2020).   See that line in the middle.

Can see in the image the line of pixels, and also on the last row of `A` and `r` there are blue pixels.  When running TC, there is row offset by a pixel,  kind of like tearing in the image.

Running older firmware (experimental branch) the issue is not present.
 
Also, a small issue...  Master brightness not applied to whole panel, just the Digit/Colon

Only the top line responded to Master brightness setting.  Hard to see, but top line is master brightness at 8%,  other lines are not effected.

![20210703_202842](https://user-images.githubusercontent.com/36442309/124351432-953f4700-dc3d-11eb-903a-4addaac647fa.jpg)

**Comment by hippyau** [comment]
I just realized the whole line is missing too :)  

This is older firmware... nice & sharp.   Exactly the same text file configs.

![20210703_205247](https://user-images.githubusercontent.com/36442309/124351971-e00e8e00-dc40-11eb-8deb-c6e8356fda9d.jpg)

**Comment by vanvught** [comment]
Same here with latest build; ghost pixels not that sharp.

> Also, a small issue... Master brightness not applied to whole panel, just the Digit/Colon

Works as designed ;-)

![IMG_4101](https://user-images.githubusercontent.com/4319913/124352604-8b97ee00-dc01-11eb-9a04-4e665ad75c2a.jpg)

**Comment by hippyau** [comment]
That is my legacy :)

**Comment by vanvught** [comment]
Got it..fixed!

**Comment by hippyau** [comment]
Confirmed, and working perfectly....  you are a legend!

![image](https://user-images.githubusercontent.com/36442309/124354551-e6f0cd00-dc4f-11eb-8357-168cb45f9c56.png)

Hahaha! :100:
