### ISSUE TITLE
DMX output: Set maximum slots

### ISSUE THREAD

**Issue by vanvught** [vanvught/rpidmx512#202]
>  A lot of very cheap LED fixtures out of China only work with the first 256 slots and get confused if slots up to 512 are sent.

cc: @hippyau

**Comment by hippyau** [comment]
Very cheap I presume...  I've worked with some cheap-ass fixutre in the
past and I've never seen one in real life that complains about more than
256 channels.   Granted, they probably do exist, just not often seen.
