### ISSUE TITLE
Network Configuration

### ISSUE THREAD

**Issue by salvonos** [vanvught/rpidmx512#21]
I am trying to connect a Raspberry PI 3 using "rpi_circle_artnet_dmx". I have copied the files to the scared and created a network.txt file. The raspberry boot but I cannot connect to the server. I have tried everything I can thing of.

network.txt

> dhcp=0
> ip_address=2.0.0.100
> net_mask=255.255.255.0
> default_gateway=2.0.0.1
> name_server=xxxx

What is the best way to setup the network file?

**Comment by vanvught** [comment]
The name_server= must be a valid IP address in your network. It can simply be the same as the default gateway. This name_server= is a quirk for the Raspberry Pi boards. Please note that I'am moving away from the Raspberry Pi boards. The next supported boards are: Orange Pi Zero / Orange Pi One:
These boards have a far better Ethernet implementation, are much cheaper. And the Opi Zero has SPI flash; it can boot from SPI flash and all configurations are stored in SPI flash. The SDCard is only needed for installing/upgrading the firmware.
