### ISSUE TITLE
Using the OrangePiZero as a recorder then as player

### ISSUE THREAD

**Issue by MarcHagen** [vanvught/rpidmx512#227]
Hi,

I've been fiddling around with the project and works great as a Artnet node.
But in a upcoming hobby project i would like to have a "headless" dmx player to spuw out DMX .
There is a player option in the current project! Great!

Now. how to record then? I have a light console where i have to program the show in. and then record the physical dmx output to a file.
Is this possible in the current project state?

**Comment by hippyau** [comment]
I have not done myself, but believe you would  playback OLA recorder files
(part of the OLA project...
https://docs.openlighting.org/ola/man/man1/ola_recorder.1.html).

These can be triggered by OSC or ArtNet with the DMX Showfile Player
firmware.... https://www.orangepi-dmx.org/8-dmx-showfile-player

**Comment by MarcHagen** [comment]
Yes i found that part, i just need a way to record from a DMX input.

**Comment by hippyau** [comment]
Yeah, currently you use OLA recorder on a Linux installation to capture
your show...

You can then playback these files back on the OrangePi.

Recording would be a nice feature @Arjan van Vught
***@***.***> :)

**Comment by MarcHagen** [comment]
Mm yeah well that the issue, i dont have a dmx usb interface (except  the orangepi) nor have i a linux install.
But if its not currently in the project then i have to find another solution,

but this would indeed be a good feature for the project :)

**Comment by hippyau** [comment]
In a spot, without a USB device you can no doubt capture (network) ArtNet
or sACN with OLA recorder to file, is configured correctly

**Comment by mrv96** [comment]
Upvote

**Comment by vanvught** [comment]
It is on my radar and todo-list. I hope to find some good free time soon. Thanks. Arjan.

**Comment by vanvught** [comment]
URL http://allwinner_34020e.local./showfile


<img width="574" alt="Scherm­afbeelding 2024-05-25 om 14 57 16" src="https://github.com/vanvught/rpidmx512/assets/4319913/8cfd98ea-8891-472b-9e2b-df405bd7754e">
<img width="563" alt="Scherm­afbeelding 2024-05-25 om 14 56 52" src="https://github.com/vanvught/rpidmx512/assets/4319913/18dc9311-ef64-46a5-89cc-d12a9f27ddb0">

**Comment by MarcHagen** [comment]
That is one massive update! Thank you very much ❤️
