### ISSUE TITLE
Implement the showfile player for all Art-Net / sACN E1.31 firmware [DMX / Pixel]

### ISSUE THREAD

**Issue by vanvught** [vanvught/rpidmx512#246]
@batecam79

**Comment by mrv96** [comment]
Upvote

**Comment by vanvught** [comment]
It is on my radar and todo-list. I hope to find some good free time soon. Thanks. Arjan.

**Comment by vanvught** [comment]
I can proudly announce that I have implemented the show file player for all Art-Net / sACN E1.31 firmware.
The latest development build is attached. Also the update Remote Configuration UI.
There is also a web page at `/showfile`.
Make sure you have a SDCard inserted at startup. There are some sample files in `showfiles.zip`
Please let me know when there are any issues. Thanks, Arjan

<img width="786" alt="Scherm­afbeelding03 19" src="https://github.com/vanvught/rpidmx512/assets/4319913/2e5db232-9243-4d60-89fe-e9f4991439a0">
<img width="574" alt="Scherm­afbeelding02 31" src="https://github.com/vanvught/rpidmx512/assets/4319913/e9d05663-7f28-4cfb-9803-55706a2a6f1e">
<img width="581" alt="Scherm­afbeelding01 56" src="https://github.com/vanvught/rpidmx512/assets/4319913/c1e455b4-e73e-4a8c-97ed-78eaff421ea2">
<img width="576" alt="Scherm­afbeelding04 50" src="https://github.com/vanvught/rpidmx512/assets/4319913/cb904d6e-0e7a-41ba-b2e0-e021922549f4">

[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/14270867/RemoteConfigUI.jar.zip)
[firmware-e131.zip](https://github.com/vanvught/rpidmx512/files/14270868/firmware-e131.zip)
[firmware-artnet.zip](https://github.com/vanvught/rpidmx512/files/14270869/firmware-artnet.zip)
[showfiles.zip](https://github.com/vanvught/rpidmx512/files/14270870/showfiles.zip)

**Comment by hippyau** [comment]
Awesome :) 😀  I'll check it out!
