### ISSUE TITLE
Implement an Art-Net node with PWM led driver PCA9685

### ISSUE THREAD

**Issue by vanvught** [vanvught/rpidmx512#272]
- [x] lib-pca9685 -> major cleanup
- [x] lib-pca9685 -> Update the examples
- [x] lib-pca9685dmx -> major cleanup
- [x] lib-pca9685dmx -> Add support for 12-bit (using 2 DMX slots).
- [x] lib-configstore -> add class StorePCA9685
- [x] lib-remoteconfig -> add support for configuration file pca9685.txt
- [x] Create project `opi_emac_artnet_rdm_pca9685`
- [x] Update Java Remote Configuration UI ([https://github.com/vanvught/Remote-Config-UI](https://github.com/vanvught/Remote-Config-UI))

@icecaster

**Comment by vanvught** [comment]
Hi Tim,

Here you are. 

See the SDCard section in https://github.com/vanvught/h3dmx512-zip for how to create the SDCard for the initial installation. 

[orangepi_zero.uImage.gz](https://github.com/vanvught/rpidmx512/files/13217720/orangepi_zero.uImage.gz)

[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/13217780/RemoteConfigUI.jar.zip)

The remote config UI is not finished; the Wizard is not implemented, yet.

For testing, I have connected 5 RGB led's. 

<img width="457" alt="Scherm­afbeelding 2023-10-31 om 15 45 12" src="https://github.com/vanvught/rpidmx512/assets/4319913/d0cc8566-ee72-4405-9e41-a53e37d57e45">

https://github.com/vanvught/rpidmx512/assets/4319913/7311cf80-1ae4-4355-ab8a-d15b203a9ad0

@icecaster

**Comment by icecaster** [comment]
Looks great!

The PCA9685 handles 12 bit, should probably use 2x artnet channels for fine dimming control?

**Comment by vanvught** [comment]
> The PCA9685 handles 12 bit, should probably use 2x artnet channels for fine dimming control?


I've just polished the 2 years old code ;-) which is just using a single channel. I will add the 12-bit support to my ToDo list.


Groet, Arjan

**Comment by vanvught** [comment]
Hi Tim,

I have added a new property `#use_8bit=0`

So per default it is 2 dmx channels per pwm channel:
```
Network init
Waiting for PHY auto negotiation to complete
Network started
Detected MX25L1605D with sector size 4096 total 2097152 bytes
[V1.0] Orange Pi Zero Compiled on Nov  3 2023 at 19:15:33
Art-Net 4 PCA9685
Network [D]
 Hostname  : allwinner_240813
 IfName    : 1: eth0 02:42:14:24:08:13
 Primary   : 192.168.2.147/24 (HTTP only 2.36.8.19)
 Gateway   : 192.168.2.1
 Broadcast : 192.168.2.255
Configuring MDNS
mDNS
 allwinner_240813.local.
 _config._udp.local. 10501 
 _tftp._udp.local. 69 
 _http._tcp.local. 80 node=Art-Net 4 PCA9685
NTP v4 Client
 Not enabled
Configuring Art-Net
RDM Device configuration
 Manufacturer Name : http://www.orangepi-dmx.org
 Manufacturer ID   : 5000
 Serial Number     : C0A80293
 Root label        : Orange Pi Zero RDM Device
 Product Category  : 0100
 Product Detail    : 0004
RDM Responder configuration
 Protocol Version 1.0
 DMX Address      : 1
 DMX Footprint    : 30
 Personality 1 of 1 [PCA9685]
 Sub Devices      : 0
 Sensors          : 1
Art-Net 4 V1.58
 Long name  : PCA9685
 Output
  Port 0  1    HTP Art-Net RDM
Bridge
 Firmware : 1.27
PCA9685 LED 16-bit
 Board instances: 1
 Channel count: 15
 DMX footprint: 30
 DMX start address: 1
Starting Art-Net
Art-Net started
```

<img width="487" alt="Scherm­afbeelding 2023-11-03 om 19 18 44" src="https://github.com/vanvught/rpidmx512/assets/4319913/b4daf99d-8f85-4c48-b253-d440e91b04e9">

[orangepi_zero.uImage.gz](https://github.com/vanvught/rpidmx512/files/13253415/orangepi_zero.uImage.gz)


@icecaster

**Comment by vanvught** [comment]
Hi Tim,

I've fixed the web-interface. 
[orangepi_zero.img.gz](https://github.com/vanvught/rpidmx512/files/13396832/orangepi_zero.img.gz)
Please use the UI in https://github.com/vanvught/rpidmx512/issues/272#issuecomment-1787373055 for upgrading the firmware.

Groet, Arjan
@icecaster

**Comment by vanvught** [comment]
Hi Tim, I have updated the Remote Configuration manager and created a new release -> https://github.com/vanvught/Remote-Config-UI/releases/tag/V25

Groet, Arjan

![Schermafbeelding 2024-01-06 om 14 17 20](https://github.com/vanvught/rpidmx512/assets/4319913/00bd2e16-eacf-4427-90ca-b891bddd1e1d)

**Comment by vanvught** [comment]
Published https://github.com/vanvught/h3dmx512-zip

**Comment by icecaster** [comment]
Amazing, thank you for your work!
