### ISSUE TITLE
Need to run as `sudo` as the http server port is below 1024

### ISSUE THREAD

**Issue by 6102051** [vanvught/rpidmx512#276]
Need to run as `sudo` as the http server port is below 1024

`sudo ./linux_e131 eno1`

```
arjanvanvught@MacBook-Air tmp % wget nuc-i7/json/e131.txt                                                        
--2021-09-02 20:19:38--  http://nuc-i7/json/e131.txt
Herleiden van nuc-i7 (nuc-i7)... 192.168.2.107
Verbinding maken met nuc-i7 (nuc-i7)|192.168.2.107|:80... verbonden.
HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Lengte: 324 [application/json]
Wordt opgeslagen als: ‘e131.txt’

e131.txt                       100%[==================================================>]     324  --.-KB/s    in 0s      

2021-09-02 20:19:38 (8,13 MB/s) - '‘e131.txt’' opgeslagen [324/324]
```

```
arjanvanvught@MacBook-Air tmp % cat e131.txt 
{"e131.txt":{"direction":"output","universe":1,"universe_port_a":1,"universe_port_b":2,"universe_port_c":3,"universe_port_d":4,"merge_mode":"htp","merge_mode_port_a":"htp","merge_mode_port_b":"htp","merge_mode_port_c":"htp","merge_mode_port_d":"htp","network_data_loss_timeout":2.5,"disable_merge_timeout":0,"priority":100}}
```

<img width="602" alt="Schermafbeelding 2021-09-02 om 20 19 13" src="https://user-images.githubusercontent.com/4319913/131896682-15e2f474-3352-4441-8e2c-fa1cf858e24f.png">

`arjanvanvught@MacBook-Air tmp % vi e131.txt`

{"e131.txt":{"direction":"output","universe":**14**,"universe_port_a":1,"universe_port_b":2,"universe_port_c":3,"universe_port_d":4,"merge_mode":"htp","merge_mode_port_a":"htp","merge_mode_port_b":"htp","merge_mode_port_c":"htp","merge_mode_port_d":"htp","network_data_loss_timeout":2.5,"disable_merge_timeout":0,"priority":100}}

```
arjanvanvught@MacBook-Air tmp % wget --post-file=e131.txt --header=Content-Type:application/json nuc-i7/submit
--2021-09-02 20:25:34--  http://nuc-i7/submit
Herleiden van nuc-i7 (nuc-i7)... 192.168.2.107
Verbinding maken met nuc-i7 (nuc-i7)|192.168.2.107|:80... verbonden.
HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Lengte: 91 [text/html]
Wordt opgeslagen als: ‘submit’

submit                         100%[==================================================>]      91  --.-KB/s    in 0s      

2021-09-02 20:25:34 (2,17 MB/s) - '‘submit’' opgeslagen [91/91]
```

```
arjanvanvught@MacBook-Air tmp % cat submit 
<!DOCTYPE html>
<html>
<head><title>Submit</title></head>
<body><h1>OK</h1></body>
</html>
```

<img width="762" alt="Schermafbeelding 2021-09-02 om 20 28 42" src="https://user-images.githubusercontent.com/4319913/131897426-2968c00d-1cb3-4a2a-a658-2e287db2b41e.png">

- [x] The Java util does not work anymore at this time -> need to fix this. 

@rbarreiros @hippyau

_Originally posted by @vanvught in https://github.com/vanvught/rpidmx512/issues/209#issuecomment-911949395_

**Comment by vanvught** [comment]
You can change the port here -> https://github.com/vanvught/rpidmx512/blob/3950ab12f9f091567438f6d3b2c4074b25a23556/lib-remoteconfig/src/httpd/httpd.cpp#L42

Note: The Mac OS X / Linux environment is for debugging purpose only.
