### ISSUE TITLE
FPP and Xlights performance 

### ISSUE THREAD

**Issue by msmorul** [vanvught/rpidmx512#281]
Using the 8x4 CLPD board with FPP test sequences and Xlights test panel, there is no output (build-in sequences work fine). The underlying issue appears to be the transmission rate from both of these is high enough that it collides w/ the DMA transfer from the PI.

Adding in barriers around spi_dma_tx_start to [Update](https://github.com/vanvught/rpidmx512/blob/master/lib-ws28xx/src/h3/ws28xxmulti.cpp#L374) as was done in [Blackout](https://github.com/vanvught/rpidmx512/blob/master/lib-ws28xx/src/h3/ws28xxmulti.cpp#L382) solved the problem.

**Comment by vanvught** [comment]
Hi @msmorul Mike, thanks for reporting this issue. I will fix it as soon as possible on the development branch. Thanks again! Arjan

**Comment by vanvught** [comment]
Firmware with fix is available -> https://github.com/vanvught/h3dmx512-zip
