### ISSUE TITLE
Compile the project

### ISSUE THREAD

**Issue by folny** [vanvught/rpidmx512#4]
Hi

I would like to ask whether it is possible to compile your projects through Windows or compilation is possible only on Linux respectively Paspberry PI.

**Comment by vanvught** [comment]
Yes, you can compile the source code in a Windows environment. An example for installing the IDE / tool-chain can be found here -> http://gnuarmeclipse.github.io/toolchain/install/

**Comment by vanvught** [comment]
For finding another solutions, the  Google search string could be : "windows arm toolchain"

**Comment by folny** [comment]
Thanks for your response, but I have a problem with creating a kernel files please can you write deployment of files in which directories should be copied and used as Circle under Windows if possible use the software to compile Eclipse Neon thank you.
