### ISSUE TITLE
bcm2835.h not found

### ISSUE THREAD

**Issue by Breidenbach** [vanvught/rpidmx512#54]
I cloned the library to my Raspberry Pi, entered the lib-tlc59711/examples directory, and tried to remake pwmled.  When I execute make, I get bcm2835.h not found.
<img width="641" alt="Screen Shot 2019-08-30 at 11 54 55 AM" src="https://user-images.githubusercontent.com/1779744/64034616-059a5000-cb1d-11e9-81b2-8a4f09a4e001.png">

**Comment by vanvught** [comment]
This indicates that the prerequisite library is missing -> https://github.com/vanvught/rpidmx512/tree/master/lib-tlc59711

> Linux Raspbian
> Prerequisite: C library for Broadcom BCM 2835 as used in Raspberry Pi

**Comment by Breidenbach** [comment]
And when I installed the library, it worked perfectly.

Thanks for the help.
