### ISSUE TITLE
ArtNet monitor mode

### ISSUE THREAD

**Issue by ThnDeh** [vanvught/rpidmx512#6]
Hi,

I try to get in monitor mode by setting output=mon to artnet.txt. If I set it to spi or dmx it works right but if I set mon it just outputs "wrong output type 'mon' using default (dmx)' ..
![img_20170410_163841](https://cloud.githubusercontent.com/assets/5053576/24864460/ef011f00-1e0c-11e7-8bbe-82e297aa4628.jpg)

Would be nice to see what my ArtNet is outputting so i know it's properly configured.

**Comment by vanvught** [comment]
The option _output=mon_ is available for the WiFi version only. I have updated http://www.raspberrypi-dmx.org/raspberry-pi-art-net-dmx-out/configuration accordingly.
