### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by ccorcos** [vanvught/rpidmx512#7]
I want to use this to control a DMX512 light. I can order your shell and burn the img onto the raspberry pi, but how to I program the pi to change the lights?

**Comment by vanvught** [comment]
There are several Raspberry Pi options for controlling a DMX512 light.

1. Raspberry Pi DMX USB Pro (http://www.raspberrypi-dmx.org/raspberry-pi-rdm-controller)
This is a bi-directional RDM controller for programs that supports the Enttec USB device.

2.  Raspberry Pi Art-Net 3 (Wifi) ->DMX Out / Pixel controller [Plug & Play] (http://www.raspberrypi-dmx.org/raspberry-pi-art-net-dmx-out)
This is a DMX output device. All popular lighting software is able to use ArtNet. There are two options: a. the wired Ethernet device, b. the Wifi device.

3. Raspberry Pi sACN E1.31 Wifi Bridge -> DMX Out [Plug & Play] (http://www.raspberrypi-dmx.org/raspberry-pi-e131-wifi-bridge)  
This is a DMX output device. All popular lighting software is able to use sACN E1.31. There is a Wifi version only.
