### ISSUE TITLE
Max7219 output.

### ISSUE THREAD

**Issue by electricforge** [vanvught/rpidmx512#9]
More of a question.
The serial output is for Max7219 only because of the device init/brightness messaging? I can decode the lsb using a 74hc595 but nothing else.
Was hoping to make a discrete driver for nixie tubes.
Could i remove all the device messages, recompile and just get the 32-bit value?

**Comment by vanvught** [comment]
Please will you provide a link to the source code where you would like to remove the device message. Thanks.
