### ISSUE TITLE
LCD 16x2 i2c display not displaying

### ISSUE THREAD

**Issue by drummerclint** [vanvught/rpidmx512#94]
Hey Arjan,

I've got a 128x64 OLED display which works like a charm but if I try to use the 16x2 display instead, it just shows a blank screen.  I've tested the display with an arduino and set the contrast and that worked just fine.  I've connected only this 1602A display to the opi with no result.  The arduino detects the display at address 0x27 and it uses the PCF 8574T i2c controller.  Any ideas as to what I could do to diagnose the issue? 

Thanks,
Clint

**Comment by vanvught** [comment]
Hi Clint,

Have you connected the VCC to +5V ? 

When you have an USB/UART cable, then you can check with the debug UART that the output is showing `Display : 2 (16,4)`

Type 2 => DISPLAY_PCF8574T_1602 -> https://github.com/vanvught/rpidmx512/blob/master/lib-display/include/display.h#L42

-Arjan

**Comment by vanvught** [comment]
![IMG_3198](https://user-images.githubusercontent.com/4319913/71327207-ebd6ab80-2505-11ea-984b-81897a931d17.jpeg)

**Comment by drummerclint** [comment]
Hey Arjan,
The display lights up but it's that's it.  I'll test the debug shortly.

Thanks,
Clint

**Comment by vanvught** [comment]
3V3 ->

![IMG_3199](https://user-images.githubusercontent.com/4319913/71327297-1d9c4200-2507-11ea-933a-546c68acf129.jpeg)

5V ->

![IMG_3200](https://user-images.githubusercontent.com/4319913/71327301-2db42180-2507-11ea-8e76-b75fb204b396.jpeg)

**Comment by drummerclint** [comment]
It's amazing how things start working when you give them the correct voltage... 
Thanks Arjan!
-Clint
